language: android
android:
  components:
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
    - addon-google_apis-google-23
    - build-tools-23.0.1
    - android-23

before_script:
- chmod +x gradlew

before_install:
- pip install --upgrade pip --user codecov

script:
- ./gradlew build

licenses:
- '.+'

after_success:
- codecov