language: android
android:
  components:
    - build-tools-21.1.2
    - android-21
    - android update sdk --no-ui --filter extra-android-support,extra-android-m2repository,extra-google-m2repository

before_script:
- chmod +x gradlew

before_install:
- openssl aes-256-cbc -K $encrypted_26e5238159b6_key -iv $encrypted_26e5238159b6_iv -in app/src/debug/res/values/google_maps_api.xml.enc -out app/src/debug/res/values/google_maps_api.xml -d
