language: android
android:
  components:
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
    - addon-google_apis-google-23
    - build-tools-23.0.1
    - android-23

before_script:
- rm app/src/debug/res/values/google_maps_api.xml.enc
- chmod +x gradlew

before_install:
- openssl aes-256-cbc -K $encrypted_26e5238159b6_key -iv $encrypted_26e5238159b6_iv -in app/src/debug/res/values/google_maps_api.xml.enc -out app/src/debug/res/values/google_maps_api.xml -d
- pip install --upgrade pip --user codecov

script:
- ./gradlew build

licenses:
- '.+'

after_success:
- codecov