language: android
android:
  components:
    - android-23
    - build-tools-23.0.1
    - extra-android-support
    - extra-android-m2repository

before_script:
- chmod +x gradlew

before_install:
- openssl aes-256-cbc -K $encrypted_26e5238159b6_key -iv $encrypted_26e5238159b6_iv -in app/src/debug/res/values/google_maps_api.xml.enc -out app/src/debug/res/values/google_maps_api.xml -d

script:
- ./gradlew build
