language: android
android:
  components:
    - tools
    - build-tools-19.1.0
    - android-19
    - platform-tools

before_script:
  - chmod +x gradlew

before_install:
- openssl aes-256-cbc -K $encrypted_dd16d61b1a0c_key -iv $encrypted_dd16d61b1a0c_iv
  -in app/src/debug/res/values/google_maps_api.xml.enc -out app/src/debug/res/values/google_maps_api.xml -d
