language: android
android:
  components:
    - android update sdk --filter platform-tools --no-ui --force > /dev/null
    - android update sdk --filter android-23 --no-ui --force > /dev/null
    - android update sdk --filter extra-android-support --no-ui --force > /dev/null
    - android update sdk --filter extra-android-m2repository --no-ui --force > /dev/null

before_script:
- chmod +x gradlew

before_install:
- openssl aes-256-cbc -K $encrypted_26e5238159b6_key -iv $encrypted_26e5238159b6_iv -in app/src/debug/res/values/google_maps_api.xml.enc -out app/src/debug/res/values/google_maps_api.xml -d
